### ISSUE TITLE
Update a post

### ISSUE THREAD

**Issue by efrapp** [lekegitrepo/facebook-clone#4]
When I'm trying to update a post and I leave the content field empty, I get the following error:
<img width="890" alt="Screen Shot 2019-12-07 at 11 00 04 AM" src="https://user-images.githubusercontent.com/698811/70377362-b31dbc00-18e1-11ea-8476-ba058ac5d602.png">

**Comment by lekegitrepo** [comment]
I fixed the issue by setting my_post to the current post if it is empty.
